from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.baseCombo = QtWidgets.QComboBox(self.centralwidget)
        self.baseCombo.setGeometry(QtCore.QRect(10, 30, 79, 23))
        self.baseCombo.setObjectName("baseCombo")
        self.convertCombo = QtWidgets.QComboBox(self.centralwidget)
        self.convertCombo.setGeometry(QtCore.QRect(100, 30, 79, 23))
        self.convertCombo.setObjectName("convertCombo")
        self.startEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.startEdit.setGeometry(QtCore.QRect(190, 30, 110, 24))
        self.startEdit.setObjectName("startEdit")
        self.stopEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.stopEdit.setGeometry(QtCore.QRect(310, 30, 110, 24))
        self.stopEdit.setObjectName("stopEdit")
        self.baseLabel = QtWidgets.QLabel(self.centralwidget)
        self.baseLabel.setGeometry(QtCore.QRect(10, 10, 59, 15))
        self.baseLabel.setObjectName("baseLabel")
        self.convertLabel = QtWidgets.QLabel(self.centralwidget)
        self.convertLabel.setGeometry(QtCore.QRect(100, 10, 71, 16))
        self.convertLabel.setObjectName("convertLabel")
        self.startlabel = QtWidgets.QLabel(self.centralwidget)
        self.startlabel.setGeometry(QtCore.QRect(190, 10, 59, 15))
        self.startlabel.setObjectName("startlabel")
        self.stopLabel = QtWidgets.QLabel(self.centralwidget)
        self.stopLabel.setGeometry(QtCore.QRect(310, 10, 59, 15))
        self.stopLabel.setObjectName("stopLabel")
        self.buildButton = QtWidgets.QPushButton(self.centralwidget)
        self.buildButton.setGeometry(QtCore.QRect(430, 30, 80, 23))
        self.buildButton.setObjectName("buildButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baseLabel.setText(_translate("MainWindow", "Base"))
        self.convertLabel.setText(_translate("MainWindow", "Convert to"))
        self.startlabel.setText(_translate("MainWindow", "Start date"))
        self.stopLabel.setText(_translate("MainWindow", "Stop date"))
        self.buildButton.setText(_translate("MainWindow", "Build!"))
